services:
  postgres:
    image: postgres:16-alpine
    container_name: learniq-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: learniq_admin
      POSTGRES_PASSWORD: learniq_password
      POSTGRES_DB: learniq_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - learniq-network

  redis:
    image: redis:7-alpine
    container_name: learniq-redis
    ports:
      - "6379:6379"
    networks:
      - learniq-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: learniq-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - learniq-network

  localstack:
    image: localstack/localstack:3.4
    container_name: learniq-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
      - PERSISTENCE=1                    # S3 verilerini volume'a kaydet
    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh"
    networks:
      - learniq-network

volumes:
  postgres-data:
  localstack-data:

networks:
  learniq-network:
    driver: bridge
