server:
  port: 8084

spring:
  application:
    name: ai-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  ai:
    openai:
      base-url: https://openrouter.ai/api
      api-key: ${OPENROUTER_API_KEY}
      chat:
        options:
          model: google/gemma-4-26b-a4b-it:free

aws:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
    bucket-name: learniq-reports
